### ISSUE TITLE
Can you make a "terms of participation" page?

### ISSUE THREAD

**Issue by draftcode** [icfpcontest2020/icfpcontest2020.github.io#1]
When participating a programming contest, my employer needs to review terms of participation (https://opensource.google/docs/hackathons/#step2). They provide some examples on what they are looking for in the terms (https://opensource.google/docs/hackathons/#modelterms). I think this terms is something like https://icfpcontest2019.github.io/rules/ in the previous ICFPCs.

It's nice if you can provide terms of participation before the contest so that I can go through the process beforehand. Is it possible to make one?

**Comment by fourdman** [comment]
+1, I'm in the same boat. I would like to participate but I need to provide the terms of the contest to my employer for review first.

**Comment by Aminopyridin** [comment]
Oh, sorry, we didn't see this issue. I'll do it soon.

**Comment by Aminopyridin** [comment]
The contest rules are [here](https://icfpcontest2020.github.io/rules.html). Hope your employer will enjoy them. Looking forward to your participation!

**Comment by fegeleiner** [comment]
The rules say you can use any language on any platform, but it seems to be much like Ford's "any colour as long as it's black".

**Comment by Aminopyridin** [comment]
@fegeleiner you can use any language and any platform. But for the part with submissions we ask for your help so that we can support your preferred language.
